
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbpipntgqqwgpixzrceb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpicGlwbnRncXF3Z3BpeHpyY2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTU2OTAsImV4cCI6MjA2MTE3MTY5MH0.DSoGP1iHkV1iXKiijtWd-x1zXHaz758Dn2NhX3jRKtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
